markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd/index.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture/index.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/9-coding-standards.md
  - docs/architecture/2-technology-stack.md
  - docs/architecture/7-source-code-organization.md
  - docs/architecture/18-configuration-system.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
